# Generated by Django 5.0.6 on 2024-06-18 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_upload", "0002_file_delete_uploadfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="files")),
            ],
        ),
        migrations.RenameModel(
            old_name="File",
            new_name="Folder",
        ),
    ]
