# Generated by Django 5.0.6 on 2024-06-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_upload", "0004_alter_folder_id_alter_folder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
