# Generated by Django 5.0.6 on 2024-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_upload", "0005_folder_slug_alter_folder_id_alter_folder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="slug",
            field=models.SlugField(blank=True, default=0, unique=True),
        ),
    ]
