# Generated by Django 5.0.6 on 2024-06-20 19:09

from django.db import migrations
from django.utils.text import slugify



def generate_unique_slug(apps, schema_editor):
    Folder = apps.get_model('app_upload', 'Folder')
    for folder in Folder.objects.all():
        if not folder.slug:
            folder.slug = slugify(f"{folder.id}-{folder.name}")
            folder.save()



class Migration(migrations.Migration):

    dependencies = [
        ("app_upload", "0008_alter_folder_slug"),
    ]

    operations = [
        migrations.RunPython(generate_unique_slug),
    ]
