# Generated by Django 5.0.6 on 2024-06-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_upload", "0011_alter_folder_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
