# Generated by Django 5.0.6 on 2024-06-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_upload", "0014_alter_uploadfile_title"),
    ]

