# Generated by Django 5.0.6 on 2024-06-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_upload", "0016_delete_uploadfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="parent_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfolders",
                to="app_upload.folder",
            ),
        ),
    ]
