# Generated by Django 5.0.6 on 2024-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_upload", "0019_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="", verbose_name="file"),
        ),
    ]
